# single instance deployment of RabbitMQ using 1 core at max, max 1GB of RAM, max 8GB of storage, with a ClusterIP service for both ingestion and UI
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: ap
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          imagePullPolicy: Always
          ports:
            - containerPort: 5672
              name: rabbitmq
            - containerPort: 15672
              name: rabbitmq-ui
          resources:
            requests:
              cpu: "500m"
              memory: 512Mi
            limits:
              cpu: "1000m"
              memory: 1Gi
          volumeMounts:
            - name: rabbitmq-persistent-storage
              mountPath: /var/lib/rabbitmq
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: silo-secrets
                  key: rabbitmq-user
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: silo-secrets
                  key: rabbitmq-pass
      volumes:
        - name: rabbitmq-persistent-storage
          persistentVolumeClaim:
            claimName: rabbitmq-persistent-storage
---
apiVersion: v1
kind: Service
metadata:
  namespace: ap
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  type: ClusterIP
  ports:
    - port: 5672
      name: rabbitmq
      targetPort: 5672
      protocol: TCP
    - port: 15672
      name: rabbitmq-ui
      targetPort: 15672
      protocol: TCP
  selector:
    app: rabbitmq
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ap
  name: rabbitmq-persistent-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi