apiVersion: apps/v1
kind: Deployment
metadata:
  name: silo
  namespace: ap
  labels:
    app: silo
    orleans/serviceId: silo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: silo
      orleans/serviceId: silo
  template:
    metadata:
      labels:
        app: silo
        orleans/serviceId: silo
        orleans/clusterId: PierogiesBot
    spec:
      containers:
        - name: silo
          image: ghcr.io/avabin/pierogiesbot/silo:tests
          imagePullPolicy: Always
          ports:
            - containerPort: 11111
              name: silo-api
            - containerPort: 30000
              name: silo-gateway
          env:
            - name: DOTNET_ENVIRONMENT
              value: "Kubernetes"
            - name: ORLEANS_SERVICE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['orleans/serviceId']
            - name: ORLEANS_CLUSTER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['orleans/clusterId']
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DOTNET_SHUTDOWNTIMEOUTSECONDS
              value: "120"
            - name: DOTNET_Blizzard__ClientId
              valueFrom:
                secretKeyRef:
                  name: silo-secrets
                  key: blizzard-client-id
            - name: DOTNET_Blizzard__ClientSecret
              valueFrom:
                secretKeyRef:
                  name: silo-secrets
                  key: blizzard-client-secret
            - name: DOTNET_Discord__Token
              valueFrom:
                secretKeyRef:
                  name: silo-secrets
                  key: discord-token
            - name: DOTNET_RabbitMQSettings__Host
              value: "rabbitmq"
            - name: DOTNET_RabbitMQSettings__UserName
              valueFrom:
                secretKeyRef:
                  name: silo-secrets
                  key: rabbitmq-user
            - name: DOTNET_RabbitMQSettings__Password
              valueFrom:
                secretKeyRef:
                  key: rabbitmq-pass
                  name: silo-secrets
            - name: DOTNET_RabbitMQSettings__VirtualHost
              value: "/"
            - name: DOTNET_RabbitMQSettings__Port
              value: "5672"
            - name: DOTNET_ConnectionStrings__MongoDB
              valueFrom:
                secretKeyRef:
                  name: silo-secrets
                  key: mongodb-connstring
            - name: DOTNET_Seq__ServerUrl
              valueFrom:
                secretKeyRef:
                  name: silo-secrets
                  key: seq-url
            - name: DOTNET_SiloType
              value: "All"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      terminationGracePeriodSeconds: 120
      imagePullSecrets:
        - name: ghcr
  minReadySeconds: 60
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0