apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
  namespace: ap
  labels:
    app: webapi
    orleans/serviceId: webapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapi
      orleans/serviceId: webapi
  template:
    metadata:
      labels:
        app: webapi
        orleans/serviceId: webapi
        orleans/clusterId: PierogiesBot
    spec:
      containers:
        - name: webapi
          image: ghcr.io/avabin/pierogiesbot/webapi:main
          imagePullPolicy: Always
          ports:
            - containerPort: 11111
              name: webapi-api
            - containerPort: 30000
              name: webapi-gateway
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Kubernetes"
            - name: ORLEANS_SERVICE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['orleans/serviceId']
            - name: ORLEANS_CLUSTER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['orleans/clusterId']
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ASPNETCORE_SHUTDOWNTIMEOUTSECONDS
              value: "120"
            - name: ASPNETCORE_RabbitMQSettings__Host
              value: "rabbitmq"
            - name: ASPNETCORE_RabbitMQSettings__UserName
              valueFrom:
                secretKeyRef:
                  name: silo-secrets
                  key: rabbitmq-user
            - name: ASPNETCORE_RabbitMQSettings__Password
              valueFrom:
                secretKeyRef:
                  key: rabbitmq-pass
                  name: silo-secrets
            - name: ASPNETCORE_RabbitMQSettings__VirtualHost
              value: "/"
            - name: ASPNETCORE_RabbitMQSettings__Port
              value: "5672"
            - name: ASPNETCORE_ConnectionStrings__MongoDB
              valueFrom:
                secretKeyRef:
                  name: silo-secrets
                  key: mongodb-connstring
            - name: ASPNETCORE_Seq__ServerUrl
              valueFrom:
                secretKeyRef:
                  name: webapi-secrets
                  key: seq-url
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      terminationGracePeriodSeconds: 120
      imagePullSecrets:
        - name: ghcr
  minReadySeconds: 60
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0