name: Test preview

on:
  pull_request_target:
    branches:
      - main
      - 'release/**'
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
      - name: Deploy Preview Environment
        # You may pin to the exact commit or the version.
        # uses: okteto/deploy-preview@43c4eec0f8cbbee12030d1f47af181834e542b9c
        uses: okteto/deploy-preview@latest
        with:
          # The name of the preview environment to create
          name: ${{ github.ref_name }}


      - name: Destroy Preview Environment
        # You may pin to the exact commit or the version.
        # uses: okteto/destroy-preview@6d681c4d1c1c69277b916601c0b67a05135d9688
        uses: okteto/destroy-preview@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # The name of the preview environment to delete
          name: ${{ github.ref_name }}
