name: Test preview

on:
  pull_request_target:
    branches:
      - main
      - 'release/**'
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:


jobs:
  review:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: compose up
        uses: isbang/compose-action@v1.4.1


      - name: Run tests
        run: dotnet test --filter "Category = ApiTests"

      - name: Test Reporter
        # You may pin to the exact commit or the version.
        # uses: dorny/test-reporter@c9b3d0e2bd2a4e96aaf424dbaa31c46b42318226
        uses: dorny/test-reporter@v1.6.0
        with:
          # Name of the check run
          name: Api Tests
          # Coma separated list of paths to test results
          path: "**/*.trx"
          reporter: all
