name: Trigger auto deployment for silo

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    paths:
      - 'src/Modules/**{cs,csproj}'
      - 'src/Services/Silo/**{cs,json,Dockerfile,csproj}'
      - '.github/workflows/silo-AutoDeployTrigger-27b23e40-05ef-4576-9917-4267f92728d1.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.SILO_REGISTRY_USERNAME }}
          password: ${{ secrets.SILO_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          # tag as commit hash and as branch name
          tags: |
            ghcr.io/ghcr.io/avabin/pierogiesbot/silo:${{ github.sha }}
            ghcr.io/ghcr.io/avabin/pierogiesbot/silo:${{ github.ref_name }}
          file: src/Services/Silo/Dockerfile
          context: .

